language: java
jdk:
  - oraclejdk7
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - marx@informatik.uni-leipzig.de
    on_success: change
    on_failure: change
after_success:
  - mvn clean 
